basePath: /
host: localhost
info:
  contact:
    email: by@artisan.io
    name: Artisan
    url: http://www.by_artisan.io/support
  description: price archive позволяет хранить информацию о ценах на товары.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: price archive [by_Artisan]
  version: "1.0"
paths:
  /api/v0/price/:
    get:
      description: Метод позволяет получить все товары
      produces:
      - application/zip
      responses:
        "200":
          description: OK
          schema:
            type: zip
      summary: Получить все товары
      tags:
      - Item
    post:
      consumes:
      - application/zip
      description: Метод позволяет записать в базу данных список продуктов
      responses:
        "200":
          description: OK
      summary: Добавить продукт
      tags:
      - Item
swagger: "2.0"
